version: "3"
services:
  backend:
    build:
      context: ./service-auth
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
  krakend_ce:
    image: devopsfaith/krakend:2.0.4
    volumes:
      - ./api-gateway:/etc/krakend
    ports:
      - "1234:1234"
      - "8080:8080"
      - "8090:8090"
    command: [ "run", "-d", "-c", "/etc/krakend/krakend.json" ]
    depends_on:
      - backend
